/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.GenericDAO;
import dao.ParametroDAO;
import entity.Parametros;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author limati
 */
public class frmParametro extends javax.swing.JDialog {

    /**
     * Creates new form frmConfiguraciones
     */
    public frmParametro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);//PARA CENTRAR EL JDIALOG
        ParametroDAO p= new ParametroDAO();
        List<Parametros> dato = p.list(1);
        
        String value = dato.get(0).getValorParam();
        
        if(value.equals("0")){
            rbtNO.setSelected(true);
        }else{
            rbtSI.setSelected(true);
        }
        
        
        
        ParametroDAO pa= new ParametroDAO();
        List<Parametros> datos = pa.list(3);
        
        String values = datos.get(0).getValorParam();
        
        if(values.equals("0")){
            rbtNOre.setSelected(true);
        }else{
            rbtSIre.setSelected(true);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtNO = new javax.swing.JRadioButton();
        rbtSI = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rbtNOre = new javax.swing.JRadioButton();
        rbtSIre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parámetro");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("1. ¿ Hoy es feriado ?");

        rbtNO.setText("NO");
        rbtNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNOActionPerformed(evt);
            }
        });

        rbtSI.setText("Sí");
        rbtSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSIActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grabar.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("2. ¿ Consultar datos a RENIEC ?");

        rbtNOre.setText("NO");
        rbtNOre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNOreActionPerformed(evt);
            }
        });

        rbtSIre.setText("Sí");
        rbtSIre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSIreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbtNO)
                        .addGap(18, 18, 18)
                        .addComponent(rbtSI))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtNOre)
                        .addGap(18, 18, 18)
                        .addComponent(rbtSIre)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtNO)
                        .addComponent(rbtSI)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtNOre)
                        .addComponent(rbtSIre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNOActionPerformed
        rbtSI.setSelected(false);
    }//GEN-LAST:event_rbtNOActionPerformed

    private void rbtSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSIActionPerformed
        rbtNO.setSelected(false);
    }//GEN-LAST:event_rbtSIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            GenericDAO g = new GenericDAO();
            Parametros p = new Parametros();
            Parametros p2 = new Parametros();

            p.setIdParam(1);
            p.setCodeParam("DIA");
            p.setNombParam("DIA");
            if(rbtNO.isSelected()==true){
                p.setValorParam("0");
            }else{
                p.setValorParam("1");
            }
            
            p2.setIdParam(3);
            p2.setCodeParam("RENIEC");
            p2.setNombParam("RENIEC");
            if(rbtNOre.isSelected()==true){
                p2.setValorParam("0");
            }else{
                p2.setValorParam("1");
            }

            g.update(p);
            g.update(p2);
            JOptionPane.showMessageDialog(null, "Guardado Exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un Error!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtNOreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNOreActionPerformed
        rbtSIre.setSelected(false);
    }//GEN-LAST:event_rbtNOreActionPerformed

    private void rbtSIreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSIreActionPerformed
        rbtNOre.setSelected(false);
    }//GEN-LAST:event_rbtSIreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmParametro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmParametro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmParametro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmParametro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmParametro dialog = new frmParametro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbtNO;
    private javax.swing.JRadioButton rbtNOre;
    private javax.swing.JRadioButton rbtSI;
    private javax.swing.JRadioButton rbtSIre;
    // End of variables declaration//GEN-END:variables
}
