/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author limati
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmPrincipal() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setIconImage(new ImageIcon(getClass().getResource("../image/logoIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProgramacion7 = new javax.swing.JButton();
        btnControlMov8 = new javax.swing.JButton();
        btnEncomienda9 = new javax.swing.JButton();
        btnVentaBoleto10 = new javax.swing.JButton();
        btnRegistrarBoleto11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnIngreso12 = new javax.swing.JButton();
        btnAflueClie13 = new javax.swing.JButton();
        btnAflueClie14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRuta1 = new javax.swing.JButton();
        btnHorario2 = new javax.swing.JButton();
        btnBus3 = new javax.swing.JButton();
        btnEmpleado5 = new javax.swing.JButton();
        btnUsuario6 = new javax.swing.JButton();
        btnRol4 = new javax.swing.JButton();
        btnConfig15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TITULO - SIS.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procesos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(309, 487));

        btnProgramacion7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnProgramacion7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/programacion.png"))); // NOI18N
        btnProgramacion7.setText("Programación");
        btnProgramacion7.setEnabled(false);
        btnProgramacion7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProgramacion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgramacion7ActionPerformed(evt);
            }
        });

        btnControlMov8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnControlMov8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/control-hoja.png"))); // NOI18N
        btnControlMov8.setText("Contol Movim.");
        btnControlMov8.setEnabled(false);
        btnControlMov8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnControlMov8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlMov8ActionPerformed(evt);
            }
        });

        btnEncomienda9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEncomienda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/encomienda.png"))); // NOI18N
        btnEncomienda9.setText("Encomienda");
        btnEncomienda9.setEnabled(false);
        btnEncomienda9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEncomienda9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomienda9ActionPerformed(evt);
            }
        });

        btnVentaBoleto10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVentaBoleto10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/boletos.png"))); // NOI18N
        btnVentaBoleto10.setText("Venta Boleto");
        btnVentaBoleto10.setEnabled(false);
        btnVentaBoleto10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVentaBoleto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaBoleto10ActionPerformed(evt);
            }
        });

        btnRegistrarBoleto11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrarBoleto11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/boletos.png"))); // NOI18N
        btnRegistrarBoleto11.setText("Registrar Boletos");
        btnRegistrarBoleto11.setEnabled(false);
        btnRegistrarBoleto11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrarBoleto11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarBoleto11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarBoleto11, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(btnVentaBoleto10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncomienda9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnControlMov8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProgramacion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnProgramacion7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnControlMov8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncomienda9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVentaBoleto10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarBoleto11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(309, 487));

        btnIngreso12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnIngreso12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ingresos.png"))); // NOI18N
        btnIngreso12.setText("Ingresos");
        btnIngreso12.setEnabled(false);
        btnIngreso12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnIngreso12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreso12ActionPerformed(evt);
            }
        });

        btnAflueClie13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAflueClie13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a-rutas.png"))); // NOI18N
        btnAflueClie13.setText("Afluencia Rutas");
        btnAflueClie13.setEnabled(false);
        btnAflueClie13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAflueClie13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAflueClie13ActionPerformed(evt);
            }
        });

        btnAflueClie14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAflueClie14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a-clientes.png"))); // NOI18N
        btnAflueClie14.setText("Afluencia Clientes");
        btnAflueClie14.setEnabled(false);
        btnAflueClie14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAflueClie14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAflueClie14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngreso12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAflueClie13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAflueClie14, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnIngreso12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAflueClie13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAflueClie14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimientos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        btnRuta1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRuta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ruta.png"))); // NOI18N
        btnRuta1.setText("Rutas");
        btnRuta1.setEnabled(false);
        btnRuta1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuta1ActionPerformed(evt);
            }
        });

        btnHorario2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHorario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hora.png"))); // NOI18N
        btnHorario2.setText("Horarios");
        btnHorario2.setEnabled(false);
        btnHorario2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnHorario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorario2ActionPerformed(evt);
            }
        });

        btnBus3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bus.png"))); // NOI18N
        btnBus3.setText("Buses");
        btnBus3.setEnabled(false);
        btnBus3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBus3ActionPerformed(evt);
            }
        });

        btnEmpleado5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEmpleado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/empleados.png"))); // NOI18N
        btnEmpleado5.setText("Empleados");
        btnEmpleado5.setEnabled(false);
        btnEmpleado5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEmpleado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleado5ActionPerformed(evt);
            }
        });

        btnUsuario6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUsuario6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usuarios.png"))); // NOI18N
        btnUsuario6.setText("Usuarios");
        btnUsuario6.setEnabled(false);
        btnUsuario6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario6ActionPerformed(evt);
            }
        });

        btnRol4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRol4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rol.png"))); // NOI18N
        btnRol4.setText("Roles");
        btnRol4.setEnabled(false);
        btnRol4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRol4ActionPerformed(evt);
            }
        });

        btnConfig15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConfig15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usuarios.png"))); // NOI18N
        btnConfig15.setText("Configuraciones");
        btnConfig15.setEnabled(false);
        btnConfig15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConfig15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfig15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRol4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRuta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHorario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpleado5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuario6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfig15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRuta1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBus3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRol4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmpleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfig15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minimize.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAflueClie13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAflueClie13ActionPerformed
        frmAfluenciaRutas c = new frmAfluenciaRutas(this, rootPaneCheckingEnabled);
        c.setVisible(true);
    }//GEN-LAST:event_btnAflueClie13ActionPerformed

    private void btnRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuta1ActionPerformed
        frmRuta pr = new frmRuta(this, rootPaneCheckingEnabled);       
        pr.setVisible(true);
        
    }//GEN-LAST:event_btnRuta1ActionPerformed

    private void btnHorario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorario2ActionPerformed
        frmHorario ho = new frmHorario(this, rootPaneCheckingEnabled);       
        ho.setVisible(true);
        
    }//GEN-LAST:event_btnHorario2ActionPerformed

    private void btnBus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBus3ActionPerformed
        frmBus bus = new frmBus(this, rootPaneCheckingEnabled);       
        bus.setVisible(true);
        
    }//GEN-LAST:event_btnBus3ActionPerformed

    private void btnRol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRol4ActionPerformed
        frmRol rol = new frmRol(this, rootPaneCheckingEnabled);       
        rol.setVisible(true);
        
    }//GEN-LAST:event_btnRol4ActionPerformed

    private void btnEmpleado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleado5ActionPerformed
        frmEmpleado em = new frmEmpleado(this, rootPaneCheckingEnabled);       
        em.setVisible(true);
        
    }//GEN-LAST:event_btnEmpleado5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario6ActionPerformed
        frmUsuario user= new frmUsuario(this, rootPaneCheckingEnabled);
        user.setVisible(true);
    }//GEN-LAST:event_btnUsuario6ActionPerformed

    private void btnProgramacion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgramacion7ActionPerformed
        frmProgramacion progra= new frmProgramacion(this, rootPaneCheckingEnabled);
        progra.setVisible(true);
    }//GEN-LAST:event_btnProgramacion7ActionPerformed

    private void btnVentaBoleto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaBoleto10ActionPerformed
        frmBoleto v = new frmBoleto(this, rootPaneCheckingEnabled);
        v.setVisible(true);
    }//GEN-LAST:event_btnVentaBoleto10ActionPerformed

    private void btnRegistrarBoleto11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBoleto11ActionPerformed
        frmRegistrarBoletos v = new frmRegistrarBoletos(this, rootPaneCheckingEnabled);
        v.setVisible(true);
    }//GEN-LAST:event_btnRegistrarBoleto11ActionPerformed

    private void btnControlMov8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlMov8ActionPerformed
        frmControl v = new frmControl(this, rootPaneCheckingEnabled);
        v.setVisible(true);
    }//GEN-LAST:event_btnControlMov8ActionPerformed

    private void btnEncomienda9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomienda9ActionPerformed
        frmEncomienda v = new frmEncomienda(this, rootPaneCheckingEnabled);
        v.setVisible(true);
    }//GEN-LAST:event_btnEncomienda9ActionPerformed

    private void btnIngreso12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreso12ActionPerformed
        frmIngresos ing = new frmIngresos(this, rootPaneCheckingEnabled);
        ing.setVisible(true);
    }//GEN-LAST:event_btnIngreso12ActionPerformed

    private void btnAflueClie14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAflueClie14ActionPerformed
        frmAfluenciaClientes r = new frmAfluenciaClientes(this, rootPaneCheckingEnabled);
        r.setVisible(true);
    }//GEN-LAST:event_btnAflueClie14ActionPerformed

    private void btnConfig15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfig15ActionPerformed
        frmParametro p = new frmParametro(this, rootPaneCheckingEnabled);
        p.setVisible(true);
    }//GEN-LAST:event_btnConfig15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAflueClie13;
    private javax.swing.JButton btnAflueClie14;
    private javax.swing.JButton btnBus3;
    private javax.swing.JButton btnConfig15;
    private javax.swing.JButton btnControlMov8;
    private javax.swing.JButton btnEmpleado5;
    private javax.swing.JButton btnEncomienda9;
    private javax.swing.JButton btnHorario2;
    private javax.swing.JButton btnIngreso12;
    private javax.swing.JButton btnProgramacion7;
    private javax.swing.JButton btnRegistrarBoleto11;
    private javax.swing.JButton btnRol4;
    private javax.swing.JButton btnRuta1;
    private javax.swing.JButton btnUsuario6;
    private javax.swing.JButton btnVentaBoleto10;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
public void activarModulos(List<Integer> perm){
    
    for (int i = 0; i < perm.size(); i++) {
        Integer numMod=perm.get(i);
        if(numMod==1){
            btnRuta1.setEnabled(true);
        }else if (numMod==2) {
            btnHorario2.setEnabled(true);
        }else if (numMod==3) {
            btnBus3.setEnabled(true);
        }else if (numMod==4) {
            btnRol4.setEnabled(true);
        }else if (numMod==5) {
            btnEmpleado5.setEnabled(true);
        }else if (numMod==6) {
            btnUsuario6.setEnabled(true);
        }else if (numMod==7) {
            btnProgramacion7.setEnabled(true);
        }else if (numMod==8) {
            btnControlMov8.setEnabled(true);
        }else if (numMod==9) {
            btnEncomienda9.setEnabled(true);
        }else if (numMod==10) {
            btnVentaBoleto10.setEnabled(true);
        }else if (numMod==11) {
            btnRegistrarBoleto11.setEnabled(true);
        }else if (numMod==12) {
            btnIngreso12.setEnabled(true);
        }else if (numMod==13) {
            btnAflueClie13.setEnabled(true);
        }else if (numMod==14) {
            btnAflueClie14.setEnabled(true);
        }else if (numMod==15) {
            btnConfig15.setEnabled(true);
        }
    }
    
    
    
    
    
}

}
