package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {


     private Integer idBol;
     private Programacion programacion;
     private Ruta ruta;
     private Usuario usuario;
     private String rucEmpr;
     private String nombEmpr;
     private String dniCli;
     private String nombCli;
     private BigDecimal precBol;
     private BigDecimal acarBol;
     private BigDecimal totaBol;
     private Date fcomBol;
     private int anumBol;

    public Boleto() {
    }

	
    public Boleto(Programacion programacion, Ruta ruta, Usuario usuario, String rucEmpr, String dniCli, String nombCli, BigDecimal precBol, BigDecimal acarBol, BigDecimal totaBol, Date fcomBol, int anumBol) {
        this.programacion = programacion;
        this.ruta = ruta;
        this.usuario = usuario;
        this.rucEmpr = rucEmpr;
        this.dniCli = dniCli;
        this.nombCli = nombCli;
        this.precBol = precBol;
        this.acarBol = acarBol;
        this.totaBol = totaBol;
        this.fcomBol = fcomBol;
        this.anumBol = anumBol;
    }
    public Boleto(Programacion programacion, Ruta ruta, Usuario usuario, String rucEmpr, String nombEmpr, String dniCli, String nombCli, BigDecimal precBol, BigDecimal acarBol, BigDecimal totaBol, Date fcomBol, int anumBol) {
       this.programacion = programacion;
       this.ruta = ruta;
       this.usuario = usuario;
       this.rucEmpr = rucEmpr;
       this.nombEmpr = nombEmpr;
       this.dniCli = dniCli;
       this.nombCli = nombCli;
       this.precBol = precBol;
       this.acarBol = acarBol;
       this.totaBol = totaBol;
       this.fcomBol = fcomBol;
       this.anumBol = anumBol;
    }
   
    public Integer getIdBol() {
        return this.idBol;
    }
    
    public void setIdBol(Integer idBol) {
        this.idBol = idBol;
    }
    public Programacion getProgramacion() {
        return this.programacion;
    }
    
    public void setProgramacion(Programacion programacion) {
        this.programacion = programacion;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRucEmpr() {
        return this.rucEmpr;
    }
    
    public void setRucEmpr(String rucEmpr) {
        this.rucEmpr = rucEmpr;
    }
    public String getNombEmpr() {
        return this.nombEmpr;
    }
    
    public void setNombEmpr(String nombEmpr) {
        this.nombEmpr = nombEmpr;
    }
    public String getDniCli() {
        return this.dniCli;
    }
    
    public void setDniCli(String dniCli) {
        this.dniCli = dniCli;
    }
    public String getNombCli() {
        return this.nombCli;
    }
    
    public void setNombCli(String nombCli) {
        this.nombCli = nombCli;
    }
    public BigDecimal getPrecBol() {
        return this.precBol;
    }
    
    public void setPrecBol(BigDecimal precBol) {
        this.precBol = precBol;
    }

    public BigDecimal getAcarBol() {
        return acarBol;
    }

    public void setAcarBol(BigDecimal acarBol) {
        this.acarBol = acarBol;
    }

    public BigDecimal getTotaBol() {
        return totaBol;
    }

    public void setTotaBol(BigDecimal totaBol) {
        this.totaBol = totaBol;
    }
    
    public Date getFcomBol() {
        return this.fcomBol;
    }
    
    public void setFcomBol(Date fcomBol) {
        this.fcomBol = fcomBol;
    }
    public int getAnumBol() {
        return this.anumBol;
    }
    
    public void setAnumBol(int anumBol) {
        this.anumBol = anumBol;
    }




}


