package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private Integer idBus;
     private String numeBus;
     private String placBus;
     private String kmetBus;
     private String marcBus;
     private String modeBus;
     private int nasiBus;
     private int estaBus;
     private int isDeleted;
     private Set programacions = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String numeBus, String placBus, String kmetBus, String marcBus, String modeBus, int nasiBus, int isDeleted) {
        this.numeBus = numeBus;
        this.placBus = placBus;
        this.kmetBus = kmetBus;
        this.marcBus = marcBus;
        this.modeBus = modeBus;
        this.nasiBus = nasiBus;
        this.isDeleted = isDeleted;
    }
    public Bus(String numeBus, String placBus, String kmetBus, String marcBus, String modeBus, int nasiBus, int isDeleted, Set programacions) {
       this.numeBus = numeBus;
       this.placBus = placBus;
       this.kmetBus = kmetBus;
       this.marcBus = marcBus;
       this.modeBus = modeBus;
       this.nasiBus = nasiBus;
       this.isDeleted = isDeleted;
       this.programacions = programacions;
    }
   
    public Integer getIdBus() {
        return this.idBus;
    }
    
    public void setIdBus(Integer idBus) {
        this.idBus = idBus;
    }
    public String getNumeBus() {
        return this.numeBus;
    }
    
    public void setNumeBus(String numeBus) {
        this.numeBus = numeBus;
    }
    public String getPlacBus() {
        return this.placBus;
    }
    
    public void setPlacBus(String placBus) {
        this.placBus = placBus;
    }
    public String getKmetBus() {
        return this.kmetBus;
    }
    
    public void setKmetBus(String kmetBus) {
        this.kmetBus = kmetBus;
    }
    public String getMarcBus() {
        return this.marcBus;
    }
    
    public void setMarcBus(String marcBus) {
        this.marcBus = marcBus;
    }
    public String getModeBus() {
        return this.modeBus;
    }
    
    public void setModeBus(String modeBus) {
        this.modeBus = modeBus;
    }
    public int getNasiBus() {
        return this.nasiBus;
    }
    
    public void setNasiBus(int nasiBus) {
        this.nasiBus = nasiBus;
    }

    public int getEstaBus() {
        return estaBus;
    }

    public void setEstaBus(int estaBus) {
        this.estaBus = estaBus;
    }
    
    
    
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getProgramacions() {
        return this.programacions;
    }
    
    public void setProgramacions(Set programacions) {
        this.programacions = programacions;
    }




}


