package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmp;
     private Rol rol;
     private String dniEmp;
     private String nombEmp;
     private String celuEmp;
     private String direEmp;
     private String nbreEmp;
     private int estaEmp;
     private int isDeleted;
     private Set programacionsForIdEpi = new HashSet(0);
     private Set programacionsForIdEco = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Rol rol, String dniEmp, String nombEmp, String celuEmp, String direEmp, String nbreEmp, int isDeleted) {
        this.rol = rol;
        this.dniEmp = dniEmp;
        this.nombEmp = nombEmp;
        this.celuEmp = celuEmp;
        this.direEmp = direEmp;
        this.nbreEmp = nbreEmp;
        this.isDeleted = isDeleted;
    }
    public Empleado(Rol rol, String dniEmp, String nombEmp, String celuEmp, String direEmp, String nbreEmp, int isDeleted, Set programacionsForIdEpi, Set programacionsForIdEco, Set usuarios) {
       this.rol = rol;
       this.dniEmp = dniEmp;
       this.nombEmp = nombEmp;
       this.celuEmp = celuEmp;
       this.direEmp = direEmp;
       this.nbreEmp = nbreEmp;
       this.isDeleted = isDeleted;
       this.programacionsForIdEpi = programacionsForIdEpi;
       this.programacionsForIdEco = programacionsForIdEco;
       this.usuarios = usuarios;
    }
   
    public Integer getIdEmp() {
        return this.idEmp;
    }
    
    public void setIdEmp(Integer idEmp) {
        this.idEmp = idEmp;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getDniEmp() {
        return this.dniEmp;
    }
    
    public void setDniEmp(String dniEmp) {
        this.dniEmp = dniEmp;
    }
    public String getNombEmp() {
        return this.nombEmp;
    }
    
    public void setNombEmp(String nombEmp) {
        this.nombEmp = nombEmp;
    }
    public String getCeluEmp() {
        return this.celuEmp;
    }
    
    public void setCeluEmp(String celuEmp) {
        this.celuEmp = celuEmp;
    }
    public String getDireEmp() {
        return this.direEmp;
    }
    
    public void setDireEmp(String direEmp) {
        this.direEmp = direEmp;
    }
    public String getNbreEmp() {
        return this.nbreEmp;
    }
    
    public void setNbreEmp(String nbreEmp) {
        this.nbreEmp = nbreEmp;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    public int getEstaEmp() {
        return estaEmp;
    }

    public void setEstaEmp(int estaEmp) {
        this.estaEmp = estaEmp;
    }
    
    
    
    public Set getProgramacionsForIdEpi() {
        return this.programacionsForIdEpi;
    }
    
    public void setProgramacionsForIdEpi(Set programacionsForIdEpi) {
        this.programacionsForIdEpi = programacionsForIdEpi;
    }
    public Set getProgramacionsForIdEco() {
        return this.programacionsForIdEco;
    }
    
    public void setProgramacionsForIdEco(Set programacionsForIdEco) {
        this.programacionsForIdEco = programacionsForIdEco;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


