package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Encomiendadetalle generated by hbm2java
 */
public class Encomiendadetalle  implements java.io.Serializable {


     private Integer idEncd;
     private Encomienda encomienda;
     private String descEnc;
     private BigDecimal precEnc;

    public Encomiendadetalle() {
    }

    public Encomiendadetalle(Encomienda encomienda, String descEnc, BigDecimal precEnc) {
       this.encomienda = encomienda;
       this.descEnc = descEnc;
       this.precEnc = precEnc;
    }
    
    public Encomiendadetalle( String descEnc, BigDecimal precEnc) {
     
       this.descEnc = descEnc;
       this.precEnc = precEnc;
    }
   
    public Integer getIdEncd() {
        return this.idEncd;
    }
    
    public void setIdEncd(Integer idEncd) {
        this.idEncd = idEncd;
    }
    public Encomienda getEncomienda() {
        return this.encomienda;
    }
    
    public void setEncomienda(Encomienda encomienda) {
        this.encomienda = encomienda;
    }
    public String getDescEnc() {
        return this.descEnc;
    }
    
    public void setDescEnc(String descEnc) {
        this.descEnc = descEnc;
    }
    public BigDecimal getPrecEnc() {
        return this.precEnc;
    }
    
    public void setPrecEnc(BigDecimal precEnc) {
        this.precEnc = precEnc;
    }




}


