package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Encomienda generated by hbm2java
 */
public class Encomienda  implements java.io.Serializable {


     private Integer idEnc;
     private Programacion programacion;
     private Ruta ruta;
     private Date fechEnc;
     private String dremEnc;
     private String nremEnc;
     private String dconEnc;
     private String nconEnc;
     private BigDecimal totaEnc;
     private int estaEnc;
     private Set encomiendadetalles = new HashSet(0);
     private Set<Encomiendadetalle> detalle;

    public Encomienda() {
    }
    public Encomienda(Integer idEnc,Programacion programacion,Ruta ruta, Date fechEnc, String dremEnc, String nremEnc, String dconEnc, String nconEnc,BigDecimal totaEnc, int estaEnc) {
        this.idEnc = idEnc;
        this.programacion = programacion;
        this.ruta = ruta;
        this.fechEnc = fechEnc;
        this.dremEnc = dremEnc;
        this.nremEnc = nremEnc;
        this.dconEnc = dconEnc;
        this.nconEnc = nconEnc;
        this.totaEnc = totaEnc;
        this.estaEnc = estaEnc;
    }
    
    public Encomienda(Programacion programacion,Ruta ruta, Date fechEnc, String dremEnc, String nremEnc, String dconEnc, String nconEnc,BigDecimal totaEnc, int estaEnc) {
        this.programacion = programacion;
        this.ruta = ruta;
        this.fechEnc = fechEnc;
        this.dremEnc = dremEnc;
        this.nremEnc = nremEnc;
        this.dconEnc = dconEnc;
        this.nconEnc = nconEnc;
        this.totaEnc = totaEnc;
        this.estaEnc = estaEnc;
    }
    public Encomienda(Programacion programacion,Ruta ruta, Date fechEnc, String dremEnc, String nremEnc, String dconEnc, String nconEnc, int estaEnc,BigDecimal totaEnc, Set encomiendadetalles) {
       this.programacion = programacion;
       this.ruta = ruta;
       this.fechEnc = fechEnc;
       this.dremEnc = dremEnc;
       this.nremEnc = nremEnc;
       this.dconEnc = dconEnc;
       this.nconEnc = nconEnc;
       this.totaEnc = totaEnc;
       this.estaEnc = estaEnc;
       this.encomiendadetalles = encomiendadetalles;
    }
   
    public Integer getIdEnc() {
        return this.idEnc;
    }
    
    public void setIdEnc(Integer idEnc) {
        this.idEnc = idEnc;
    }
    public Programacion getProgramacion() {
        return this.programacion;
    }
    
    public void setProgramacion(Programacion programacion) {
        this.programacion = programacion;
    }

    public Ruta getRuta() {
        return ruta;
    }

    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    
    public Date getFechEnc() {
        return this.fechEnc;
    }
    
    public void setFechEnc(Date fechEnc) {
        this.fechEnc = fechEnc;
    }
    public String getDremEnc() {
        return this.dremEnc;
    }
    
    public void setDremEnc(String dremEnc) {
        this.dremEnc = dremEnc;
    }
    public String getNremEnc() {
        return this.nremEnc;
    }
    
    public void setNremEnc(String nremEnc) {
        this.nremEnc = nremEnc;
    }
    public String getDconEnc() {
        return this.dconEnc;
    }
    
    public void setDconEnc(String dconEnc) {
        this.dconEnc = dconEnc;
    }
    public String getNconEnc() {
        return this.nconEnc;
    }
    
    public void setNconEnc(String nconEnc) {
        this.nconEnc = nconEnc;
    }

    public BigDecimal getTotaEnc() {
        return totaEnc;
    }

    public void setTotaEnc(BigDecimal totaEnc) {
        this.totaEnc = totaEnc;
    }
    
    
    
    public int getEstaEnc() {
        return this.estaEnc;
    }
    
    public void setEstaEnc(int estaEnc) {
        this.estaEnc = estaEnc;
    }
    public Set getEncomiendadetalles() {
        return this.encomiendadetalles;
    }
    
    public void setEncomiendadetalles(Set encomiendadetalles) {
        this.encomiendadetalles = encomiendadetalles;
    }

    public Set<Encomiendadetalle> getDetalle() {
        return detalle;
    }

    public void setDetalle(Set<Encomiendadetalle> detalle) {
        this.detalle = detalle;
    }

    


}


