package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHor;
     private String saliHor;
     private String llegHor;
     private int isDeleted;
     private Set programacions = new HashSet(0);

    public Horario() {
    }

	
    public Horario(String saliHor, String llegHor, int isDeleted) {
        this.saliHor = saliHor;
        this.llegHor = llegHor;
        this.isDeleted = isDeleted;
    }
    public Horario(String saliHor, String llegHor, int isDeleted, Set programacions) {
       this.saliHor = saliHor;
       this.llegHor = llegHor;
       this.isDeleted = isDeleted;
       this.programacions = programacions;
    }
   
    public Integer getIdHor() {
        return this.idHor;
    }
    
    public void setIdHor(Integer idHor) {
        this.idHor = idHor;
    }
    public String getSaliHor() {
        return this.saliHor;
    }
    
    public void setSaliHor(String saliHor) {
        this.saliHor = saliHor;
    }
    public String getLlegHor() {
        return this.llegHor;
    }
    
    public void setLlegHor(String llegHor) {
        this.llegHor = llegHor;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getProgramacions() {
        return this.programacions;
    }
    
    public void setProgramacions(Set programacions) {
        this.programacions = programacions;
    }




}


