package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private Integer idMov;
     private Control control;
     private String tipoMov;
     private String nombMov;
     private BigDecimal montMov;

    public Movimiento() {
    }

    public Movimiento(Control control, String tipoMov, String nombMov, BigDecimal montMov) {
       this.control = control;
       this.tipoMov = tipoMov;
       this.nombMov = nombMov;
       this.montMov = montMov;
    }
   
    public Integer getIdMov() {
        return this.idMov;
    }
    
    public void setIdMov(Integer idMov) {
        this.idMov = idMov;
    }
    public Control getControl() {
        return this.control;
    }
    
    public void setControl(Control control) {
        this.control = control;
    }
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }
    public String getNombMov() {
        return this.nombMov;
    }
    
    public void setNombMov(String nombMov) {
        this.nombMov = nombMov;
    }
    public BigDecimal getMontMov() {
        return this.montMov;
    }
    
    public void setMontMov(BigDecimal montMov) {
        this.montMov = montMov;
    }




}


