package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1



/**
 * Parametros generated by hbm2java
 */
public class Parametros  implements java.io.Serializable {


     private Integer idParam;
     private String codeParam;
     private String nombParam;
     private String valorParam;

    public Parametros() {
    }

    public Parametros(String codeParam, String nombParam, String valorParam) {
       this.codeParam = codeParam;
       this.nombParam = nombParam;
       this.valorParam = valorParam;
    }
    
    public Parametros(Integer idParam,String codeParam, String nombParam, String valorParam) {
       this.idParam = idParam;
       this.codeParam = codeParam;
       this.nombParam = nombParam;
       this.valorParam = valorParam;
    }
   
    public Integer getIdParam() {
        return this.idParam;
    }
    
    public void setIdParam(Integer idParam) {
        this.idParam = idParam;
    }
    public String getCodeParam() {
        return this.codeParam;
    }
    
    public void setCodeParam(String codeParam) {
        this.codeParam = codeParam;
    }
    public String getNombParam() {
        return this.nombParam;
    }
    
    public void setNombParam(String nombParam) {
        this.nombParam = nombParam;
    }
    public String getValorParam() {
        return this.valorParam;
    }
    
    public void setValorParam(String valorParam) {
        this.valorParam = valorParam;
    }




}


