package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1



/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer idPer;
     private Rol rol;
     private int nmodPer;

    public Permiso() {
    }

    public Permiso(Rol rol, int nmodPer) {
       this.rol = rol;
       this.nmodPer = nmodPer;
    }
    
    public Permiso(int nmodPer) {
       this.nmodPer = nmodPer;
    }
   
    public Integer getIdPer() {
        return this.idPer;
    }
    
    public void setIdPer(Integer idPer) {
        this.idPer = idPer;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public int getNmodPer() {
        return this.nmodPer;
    }
    
    public void setNmodPer(int nmodPer) {
        this.nmodPer = nmodPer;
    }




}


