package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Programacion generated by hbm2java
 */
public class Programacion  implements java.io.Serializable {


     private Integer idPro;
     private Bus bus;
     private Empleado empleadoByIdEpi;
     private Empleado empleadoByIdEco;
     private Horario horario;
     private Ruta ruta;
     private Date fechPro;
     private int asidPro;
     private String hllegaPro;
     private int estaPro;
     private Set boletos = new HashSet(0);
     private Set encomiendas = new HashSet(0);
     private Set controls = new HashSet(0);

    public Programacion() {
    }

	
    public Programacion(Bus bus, Empleado empleadoByIdEpi, Empleado empleadoByIdEco, Horario horario, Ruta ruta, Date fechPro, int asidPro, String hllegaPro, int estaPro) {
        this.bus = bus;
        this.empleadoByIdEpi = empleadoByIdEpi;
        this.empleadoByIdEco = empleadoByIdEco;
        this.horario = horario;
        this.ruta = ruta;
        this.fechPro = fechPro;
        this.asidPro = asidPro;
        this.hllegaPro = hllegaPro;
        this.estaPro = estaPro;
    }
    public Programacion(Bus bus, Empleado empleadoByIdEpi, Empleado empleadoByIdEco, Horario horario, Ruta ruta, Date fechPro, int asidPro, String hllegaPro, int estaPro, Set boletos, Set encomiendas, Set controls) {
       this.bus = bus;
       this.empleadoByIdEpi = empleadoByIdEpi;
       this.empleadoByIdEco = empleadoByIdEco;
       this.horario = horario;
       this.ruta = ruta;
       this.fechPro = fechPro;
       this.asidPro = asidPro;
       this.hllegaPro = hllegaPro;
       this.estaPro = estaPro;
       this.boletos = boletos;
       this.encomiendas = encomiendas;
       this.controls = controls;
    }
   
    public Integer getIdPro() {
        return this.idPro;
    }
    
    public void setIdPro(Integer idPro) {
        this.idPro = idPro;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public Empleado getEmpleadoByIdEpi() {
        return this.empleadoByIdEpi;
    }
    
    public void setEmpleadoByIdEpi(Empleado empleadoByIdEpi) {
        this.empleadoByIdEpi = empleadoByIdEpi;
    }
    public Empleado getEmpleadoByIdEco() {
        return this.empleadoByIdEco;
    }
    
    public void setEmpleadoByIdEco(Empleado empleadoByIdEco) {
        this.empleadoByIdEco = empleadoByIdEco;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Date getFechPro() {
        return this.fechPro;
    }
    
    public void setFechPro(Date fechPro) {
        this.fechPro = fechPro;
    }
    public int getAsidPro() {
        return this.asidPro;
    }
    
    public void setAsidPro(int asidPro) {
        this.asidPro = asidPro;
    }
    public String getHllegaPro() {
        return this.hllegaPro;
    }
    
    public void setHllegaPro(String hllegaPro) {
        this.hllegaPro = hllegaPro;
    }
    public int getEstaPro() {
        return this.estaPro;
    }
    
    public void setEstaPro(int estaPro) {
        this.estaPro = estaPro;
    }
    public Set getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set boletos) {
        this.boletos = boletos;
    }
    public Set getEncomiendas() {
        return this.encomiendas;
    }
    
    public void setEncomiendas(Set encomiendas) {
        this.encomiendas = encomiendas;
    }
    public Set getControls() {
        return this.controls;
    }
    
    public void setControls(Set controls) {
        this.controls = controls;
    }




}


