package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombRol;
     private String descRol;
     private int isDeleted;
     private Set empleados = new HashSet(0);
     private Set permisos = new HashSet(0);
     private Set<Permiso> permiso;

    public Rol() {
    }

	
    public Rol(String nombRol, String descRol, int isDeleted) {
        this.nombRol = nombRol;
        this.descRol = descRol;
        this.isDeleted = isDeleted;
    }
    
    public Rol(Integer idRol,String nombRol, String descRol, int isDeleted) {
        this.idRol = idRol;
        this.nombRol = nombRol;
        this.descRol = descRol;
        this.isDeleted = isDeleted;
    }
    
    public Rol(Integer idRol) {
        this.idRol = idRol;
    }
    
    public Rol(String nombRol, String descRol, int isDeleted, Set empleados, Set permisos) {
       this.nombRol = nombRol;
       this.descRol = descRol;
       this.isDeleted = isDeleted;
       this.empleados = empleados;
       this.permisos = permisos;
    }

    
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombRol() {
        return this.nombRol;
    }
    
    public void setNombRol(String nombRol) {
        this.nombRol = nombRol;
    }
    public String getDescRol() {
        return this.descRol;
    }
    
    public void setDescRol(String descRol) {
        this.descRol = descRol;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }

    public Set<Permiso> getPermiso() {
        return permiso;
    }

    public void setPermiso(Set<Permiso> permiso) {
        this.permiso = permiso;
    }




}


