package entity;
// Generated 05-jun-2017 19:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsu;
     private Empleado empleado;
     private String logiUsu;
     private String passUsu;
     private int isDeleted;
     private Set controls = new HashSet(0);
     private Set boletos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Empleado empleado, String logiUsu, String passUsu, int isDeleted) {
        this.empleado = empleado;
        this.logiUsu = logiUsu;
        this.passUsu = passUsu;
        this.isDeleted = isDeleted;
    }
    public Usuario(Empleado empleado, String logiUsu, String passUsu, int isDeleted, Set controls, Set boletos) {
       this.empleado = empleado;
       this.logiUsu = logiUsu;
       this.passUsu = passUsu;
       this.isDeleted = isDeleted;
       this.controls = controls;
       this.boletos = boletos;
    }
   
    public Integer getIdUsu() {
        return this.idUsu;
    }
    
    public void setIdUsu(Integer idUsu) {
        this.idUsu = idUsu;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getLogiUsu() {
        return this.logiUsu;
    }
    
    public void setLogiUsu(String logiUsu) {
        this.logiUsu = logiUsu;
    }
    public String getPassUsu() {
        return this.passUsu;
    }
    
    public void setPassUsu(String passUsu) {
        this.passUsu = passUsu;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getControls() {
        return this.controls;
    }
    
    public void setControls(Set controls) {
        this.controls = controls;
    }
    public Set getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set boletos) {
        this.boletos = boletos;
    }




}


